name: HulplijnStefan
main: ghost_gaming.plugin.hulplijnstefan.HulplijnStefan
version: 1.1
commands:
    stefan:
        description: Voegt een bericht toe aan stefans hulplijn
        usage: /<command> <args>
